services:
  api_compras:
    image: api
    build:
      context: .
    container_name: api_compras
    ports:
      - 8081:8081
    volumes:
      - app_logs:/logs
    depends_on:
      - elasticsearch
      - postgresql
    networks:
      - api_net
    environment:
      - API_COMPRAS_PSQL_SENHA=${API_COMPRAS_PSQL_SENHA}
      - API_COMPRAS_PSQL_USUARIO=${API_COMPRAS_PSQL_USUARIO}
      - POSTGRES_USER=${API_COMPRAS_PSQL_USUARIO}
      - POSTGRES_PASSWORD=${API_COMPRAS_PSQL_SENHA}
      - POSTGRES_DB=comprasdb

  postgresql:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${API_COMPRAS_PSQL_USUARIO}
      - POSTGRES_PASSWORD=${API_COMPRAS_PSQL_SENHA}
      - POSTGRES_DB=comprasdb
      - API_COMPRAS_PSQL_SENHA=${API_COMPRAS_PSQL_SENHA}
      - API_COMPRAS_PSQL_USUARIO=${API_COMPRAS_PSQL_USUARIO}
    networks:
      - api_net
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - api_net
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - api_net
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    container_name: filebeat
    user: root
    command: --strict.perms=false -e
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - app_logs:/logs
    networks:
      - api_net
    depends_on:
      - elasticsearch
      - kibana

volumes:
  esdata:
  app_logs:

networks:
  api_net:
    driver: bridge