CREATE TABLE IF NOT EXISTS comprador (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(30) NOT NULL,
    saldo_total NUMERIC NOT NULL,
    saldo_debito NUMERIC NOT NULL,
    saldo_vale_alimentacao NUMERIC NOT NULL,
    total_compras SMALLINT NOT NULL,
    data_criacao TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS produto (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(30) NOT NULL,
    preco NUMERIC NOT NULL,
    data_criacao TIMESTAMP DEFAULT NOW(),
    data_modificacao TIMESTAMP DEFAULT NOW()
);