name: Testar a aplicação
run-name: ${{ github.actor }} - Testes da aplicação
on:
  push:
    branches:
      - main
jobs:
  rodar-testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Executar os testes
        run: mvn clean test
  tentar-compilar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Compilar o projeto
        run: mvn clean compile

